// Generated by scripts/export_contracts.py. Do not edit.

export type Alert = {
  acknowledgement_timestamp?: string | null;
  alert_category: string;
  alert_id: string;
  asset_criticality?: Severity | null;
  asset_id?: string | null;
  case_id?: string | null;
  closure_reason?: string | null;
  closure_timestamp?: string | null;
  cse_id: string;
  disposition?: string | null;
  escalation_required?: boolean | null;
  escalation_timestamp?: string | null;
  escalation_type?: string | null;
  investigation_start_timestamp?: string | null;
  provenance: Provenance;
  rule_use_case: string;
  severity: Severity;
  source: string;
  timestamp: string;
};

export type AnalyticsRun = {
  analytics_version: string;
  assessment_period: AssessmentPeriod;
  completed_at?: string | null;
  configuration: Record<string, unknown>;
  configuration_hash: string;
  dataset_hash: string;
  dataset_id: string;
  execution_seconds?: number | null;
  findings_generated?: number;
  records_analysed?: number;
  run_id: string;
  software_version: string;
  started_at: string;
  status: "queued" | "running" | "completed" | "failed";
};

export type Artifact = {
  filename: string;
  row_count: number;
  sha256: string;
};

export type AssessmentPeriod = {
  end: string;
  start: string;
};

export type Asset = {
  asset_id: string;
  criticality: Severity;
  cse_id: string;
  environment: string;
  monitoring_expected: boolean;
  monitoring_source?: string | null;
  provenance: Provenance;
  system_type: string;
};

export type AuditEvent = {
  action: string;
  actor: string;
  details?: Record<string, unknown>;
  event_id: string;
  object_id: string;
  role: Role;
  timestamp: string;
};

export type CSE = {
  assessment_period: AssessmentPeriod;
  criticality: Severity;
  cse_id: string;
  entity_size?: "small" | "medium" | "large";
  name: string;
  peer_group: string;
  provenance: Provenance;
  sector: string;
};

export type Case = {
  assigned_team?: string | null;
  case_id: string;
  closed_at?: string | null;
  closure_reason?: string | null;
  cse_id: string;
  escalation_status?: string | null;
  escalation_timestamp?: string | null;
  investigation_duration?: number | null;
  investigation_steps_count?: number | null;
  investigator?: string | null;
  linked_alert_count?: number | null;
  opened_at: string;
  provenance: Provenance;
  remediation_status?: string | null;
  root_cause?: string | null;
  severity: Severity;
};

export type Contract = {
};

export type DatasetManifest = {
  artifacts: ReadonlyArray<Artifact>;
  assessment_period: AssessmentPeriod;
  created_at: string;
  dataset_hash: string;
  dataset_id: string;
  generator_version?: string | null;
  schema_version: string;
  seed?: number | null;
};

export type DatasetVersion = {
  artifacts: ReadonlyArray<Artifact>;
  assessment_period: AssessmentPeriod;
  created_at: string;
  dataset_hash: string;
  dataset_id: string;
  generator_version?: string | null;
  schema_version: string;
  seed?: number | null;
};

export type EntityRecord = {
  cse_id: string;
  provenance: Provenance;
};

export type EscalationRecord = {
  alert_id: string;
  case_id?: string | null;
  cse_id: string;
  escalation_id: string;
  escalation_type: string;
  provenance: Provenance;
  receiving_team: string;
  timestamp: string;
};

export type EvidenceReference = {
  cse_id: string;
  dataset_id: string;
  provenance: Provenance;
  record_id: string;
  record_type: "cses" | "alerts" | "cases" | "assets" | "investigation_events" | "escalations";
};

export type HealthStatus = {
  demo_mode: boolean;
  message: string;
  registered_datasets: number | null;
  service?: "sat-sa-api";
  software_version?: string;
  status: "ok" | "unavailable";
  storage_ready: boolean;
};

export type InvestigationEvent = {
  action: string;
  actor_team: string;
  case_id: string;
  cse_id: string;
  event_id: string;
  event_type: string;
  evidence_reference?: string | null;
  notes_length?: number | null;
  outcome?: string | null;
  provenance: Provenance;
  timestamp: string;
};

export type Provenance = {
  ingestion_batch: string;
  source_file: string;
  source_record: string;
  transformation_version: string;
};

export type ReviewDecision = {
  actor: string;
  cse_id: string;
  decision_id: string;
  note?: string;
  outcome: ReviewOutcome;
  role: Role;
  signal_id: string;
  timestamp: string;
};

export type ReviewOutcome = "accepted" | "dismissed" | "explained" | "confirmed_concern" | "false_positive" | "insufficient_evidence" | "further_investigation";

export type Role = "reader" | "examiner" | "administrator";

export type Severity = "critical" | "high" | "medium" | "low" | "informational";

export type SupervisorySignal = {
  calculation_version: string;
  category: "detection" | "investigation" | "escalation" | "incident_response" | "security_operations" | "governance" | "operational_discipline" | "cyber_resilience";
  confidence: "limited" | "medium" | "high";
  cse_id: string;
  data_completeness: number;
  description: string;
  evidence_count: number;
  evidence_references: ReadonlyArray<EvidenceReference>;
  inferred_signal: string;
  methodology: string;
  name: string;
  observed_evidence: string;
  run_id: string;
  severity: Severity;
  signal_id: string;
  signal_strength: "low" | "medium" | "high";
  supervisory_hypothesis: string;
  thresholds: Record<string, unknown>;
};
