from pathlib import Path
from typing import Protocol
from sat_sa_contracts.models import AuditEvent, DatasetManifest, DatasetVersion, EntityRecord


class MetadataRepository(Protocol):
    def initialize(self) -> None: ...
    def register_dataset(self, dataset: DatasetVersion) -> None: ...
    def get_dataset(self, dataset_id: str) -> DatasetVersion | None: ...
    def append_audit(self, event: AuditEvent) -> None: ...
    def status(self) -> dict: ...
    def close(self) -> None: ...


class EvidenceRepository(Protocol):
    def write_dataset(self, records: dict[str, list[EntityRecord]], destination: Path, *, seed: int) -> DatasetManifest: ...
    def read_records(self, dataset_id: str, record_type: str, cse_id: str, *, limit: int = 100, offset: int = 0) -> list[EntityRecord]: ...
