"""Generate JSON schema and TypeScript from Pydantic; --check never writes."""
import argparse
import json
from pathlib import Path

from sat_sa_contracts import models


def ts_type(schema: dict) -> str:
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(v) for v in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(s) for s in schema["anyOf"])
    kind = schema.get("type")
    if kind == "array":
        return f"ReadonlyArray<{ts_type(schema['items'])}>"
    if kind == "object":
        if "properties" in schema:
            required = schema.get("required", [])
            return "{\n" + "".join(f"  {key}{'' if key in required else '?'}: {ts_type(value)};\n" for key, value in sorted(schema["properties"].items())) + "}"
        additional = schema.get("additionalProperties", {})
        return "Record<string, " + (ts_type(additional) if isinstance(additional, dict) else "unknown") + ">"
    if kind in ("string", "boolean", "null"):
        return kind
    if kind in ("number", "integer"):
        return "number"
    if not schema:
        return "unknown"
    raise ValueError(f"Unsupported JSON schema: {schema}")


def artifacts() -> dict[str, bytes]:
    definitions = {}
    outputs = {}
    for name, cls in sorted(vars(models).items()):
        if isinstance(cls, type) and issubclass(cls, models.Contract) and cls.__module__ == models.__name__:
            schema = cls.model_json_schema()
            outputs[f"data/schemas/{name}.json"] = (json.dumps(schema, sort_keys=True, indent=2) + "\n").encode()
            definitions.update(schema.get("$defs", {}))
            definitions[name] = {k: v for k, v in schema.items() if k != "$defs"}
    ts = "// Generated by scripts/export_contracts.py. Do not edit.\n\n"
    ts += "\n\n".join(f"export type {name} = {ts_type(schema)};" for name, schema in sorted(definitions.items())) + "\n"
    outputs["packages/shared-types/src/generated.ts"] = ts.encode()
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    drift = []
    outputs = artifacts()
    for name, content in outputs.items():
        path = args.output_root / name
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                drift.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)
    schema_dir = args.output_root / "data/schemas"
    stale = [p for p in schema_dir.glob("*.json") if p.relative_to(args.output_root).as_posix() not in outputs]
    if stale:
        drift.extend(str(p) for p in stale)
    if drift:
        print("Contract drift: " + ", ".join(drift))
        return 1
    print(f"Contracts {'verified' if args.check else 'generated'}: {len(outputs)} artifacts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
